### ISSUE TITLE
Toc Observer Unexpected Behavior (Wrong index)

### ISSUE THREAD

**Issue by dreamy32** [spaciousejar/learn-git-with-me#15]
The Toc observers seems to be working as expected on the first clicks, but it loses track of the right index. I supposed that due to the style being applied to the wrong toc.

See below GIF for demo:
![0a0db54dbc83c5bc6f68fb4294059e0f](https://github.com/user-attachments/assets/40ee2e13-cac9-44f4-9c0a-34f68f8c45b5)

**Comment by spaciousejar** [comment]
I believe this works perfectly.

**Comment by dreamy32** [comment]
> I believe this works perfectly.

I appreciate your feedback! I found it Weird to highlight On Windows but not the other sections such as MacOs, Linux. 

There might be a confusion on my part, if you find time to enlighten me, it would be greatly appreciated.
